cluster_label: "test_cluster"
provider: "aws"

private_rsa_key_path: "/Users/vanderlei/.ssh/id_rsa"
public_rsa_key_path: "/Users/vanderlei/.ssh/id_rsa.pub"
public_key_name: "vanderlei@MAC.local"

aws_secret_key: ""
aws_access_key: ""

master_ami: "ami-06595df5f34c718e5"
master_instance_type: "t3.2xlarge"
master_rbs_size: 50
master_rbs_type: "io1"
master_rbs_iops: 150

worker_count: 1
worker_ami: "ami-06595df5f34c718e5"
worker_instance_type: "t3.2xlarge"
worker_rbs_size: 50
worker_rbs_type: "io1"
worker_rbs_iops: 150

worker_spot_price: 0.5

experiment_tag: "generic-test"
