cluster_label: "test_cluster"
provider: "aws-spot"

private_rsa_key_path: "~/.ssh/id_rsa"
public_rsa_key_path: "~/.ssh/id_rsa.pub"
public_key_name: "clement@clement-Nitro-AN515-51"

aws_secret_key: "uyL1y/dCD8iLS3g+kdiaFUy9+w6ZBDLfox6+VHEI"
aws_access_key: "AKIA3K4RAFVMNJTOTKMC"

master_ami: "ami-06595df5f34c718e5"
master_instance_type: "t3.2xlarge"
master_rbs_size: 50
master_rbs_type: "io1"
master_rbs_iops: 150

worker_count: 1
worker_ami: "ami-06595df5f34c718e5"
worker_instance_type: "t3.2xlarge"
worker_rbs_size: 50
worker_rbs_type: "io1"
worker_rbs_iops: 150

worker_spot_price: 0.5

experiment_tag: "generic-test"
